[WIP] Bug/malformed descriptions
zilverline/mt940 pull request #38
Opened 2020-10-26 14:34 UTC by stephanvd

2020-11-02 10:49 UTC, lvonk reviewed
Not sure if `m` does anything?

2020-11-02 12:30 UTC, stephanvd commented on lib/mt940_structured/parsers/abnamro/transaction_parser.rb
> +      line_86 = line_86.gsub(/:86:/m, '')
line 86 can be multiline now, not really needed in this case but for consistency

2020-11-02 12:30 UTC, stephanvd commented on lib/mt940_structured/parsers/sns/transaction_parser.rb
>        line_86 = line_86.gsub(/:86:/, '')
missed that one :)

2020-11-02 12:32 UTC, stephanvd commented on spec/mt940_abnamro_spec.rb
> +          expect(@transaction.description).to eq('KPN - DIGITENNE    BETALINGSKENM.  0000000421886595314606715                       BETREFT FACTUUR D.D. 20-05-2011INCL. 1,44 BTW')
if i understand correctly we only add newlines for repeating :86: lines. not for blank follow up lines

2020-11-02 12:42 UTC, lvonk commented on spec/mt940_abnamro_spec.rb
> +          expect(@transaction.description).to eq('KPN - DIGITENNE    BETALINGSKENM.  0000000421886595314606715                       BETREFT FACTUUR D.D. 20-05-2011INCL. 1,44 BTW')
What I mean is shouldn't we have to keep the existing newline in this case (looking at the mt940 file)

2020-11-03 08:39 UTC, bforma requested changes

2020-11-03 08:39 UTC, bforma commented on lib/mt940_structured/file_content.rb
> +    @raw_lines = raw_lines.map(&:rstrip)
I think we should avoid touching the original lines at all. That will only lead to differences with data from bank data providers.

2020-11-03 13:09 UTC, merged